Traceback (most recent call last):
  File "../../process.py", line 12, in <module>
    main()
  File "/Users/jdeck/IdeaProjects/ppo-data-pipeline/process/process.py", line 260, in main
    config = Config(**args.__dict__)
  File "/Users/jdeck/IdeaProjects/ppo-data-pipeline/process/config.py", line 93, in __init__
    self._add_default_rules()
  File "/Users/jdeck/IdeaProjects/ppo-data-pipeline/process/config.py", line 198, in _add_default_rules
    self._parse_list(list_name)
  File "/Users/jdeck/IdeaProjects/ppo-data-pipeline/process/config.py", line 178, in _parse_list
    "Invalid rule. Can't find specified list \"{}\"".format(file_path))
AttributeError: Invalid rule. Can't find specified list "test/test_npn/phenophase_descriptions.csv"
